---
# File: module_enable.yml
# Part: Apache
#         
# Description: Enable an Apache server
#
# Parameters:
# - $module: module name (ex. rewrite) 
#
# Dependencies ([part:]type:filename):
# - handlers:handlers.yml
#
# OS: Ubuntu

- name: Apache | Enable module | Enable $module
  command: a2enmod $module creates=/etc/apache2/mods-enabled/$module.load
  notify: 
  - apache-restart

