---
- name: Install default package
  apt: pkg=memcached state=present

- name: Push default configuration template
  template:
    src=memcached.conf.j2
    dest=/etc/memcached.conf
    owner=root group=root mode=0644
  notify:
  - memcached-restart

# Ensure service is running.
- name: Ensure deamon is running correctly
  service: name=memcached state=started
