---

- name: PHP5 | Apache2 | Backup configuration
  shell: creates=/etc/php5/apache2/php.ini.orig cp /etc/php5/apache2/php.ini /etc/php5/apache2/php.ini.orig
  register: result
- fetch: src=/etc/php5/apache2/php.ini.orig dest=fetched
  when: result|changed
- name: PHP5 | Apache2 | Deploy configuration
  template: src=apache2_php.ini.j2 dest=/etc/php5/apache2/php.ini mode=0644 owner=root group=root backup=yes
  notify: restart apache2
  register: result
- fetch: src=/etc/php5/apache2/php.ini dest=fetched
  when: result|changed
