---
# File: main.yml
# Type: task
# Part: NodeJS

## Install
- name: Add Chris-Lea nodejs repository
  apt_repository: repo="ppa:chris-lea/node.js"

- name: Install Node + NPM packages
  apt: pkg=nodejs state={{ nodejs_apt_state }} update_cache=yes

## Install global packages
- name: NodeJS | NPM | Install global packages
  npm: name={{ item }} global=yes state={{ nodejs_apt_state }} registry={{ nodejs_npm_registry }}
  when: nodejs_npm_modules is defined
  with_items: nodejs_npm_modules
