---

- name: pecl | Insure PHP development packages are installed
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-dev
    - php-pear
    - make

- name: pecl | Test for previous "{{ package }}" install
  shell:  pecl list | grep -i '{{ package }}'
  register: php_package_exists
  ignore_errors: yes

- name: pecl | Install {{ package }}-{{ version }}
  shell: echo {{ stdin }} | pecl install {{ package }}-{{ version }}
  when: php_package_exists|failed

- name: pecl | Set {{ package }} config (Ubuntu == 12.04)
  template:
    src={{ package }}.ini.j2
    dest=/etc/php5/conf.d/{{ package }}.ini
    owner=root group=root mode=0644
  when: ansible_lsb.release == "12.04"

- name: pecl | Set {{ package }} config (Ubuntu > 12.04)
  template:
    src={{ package }}.ini.j2
    dest=/etc/php5/mods-available/{{ package }}.ini
    owner=root group=root mode=0644
  when: ansible_lsb.release != "12.04"

- name: pecl | Set symbolic link to {{ package }} config (Ubuntu > 12.04)
  file:
    src=/etc/php5/mods-available/{{ package }}.ini
    dest=/etc/php5/conf.d/20-{{ package }}.ini
    owner=root group=root state=link
  when: ansible_lsb.release != "12.04"

# When PHP is running
#- name: PHP | PECL | Notifying FPM to restart (if it is running)
#  debug: msg="Restart PHP-FPM"
#  when_failed: ${php_package_exists}
#  notify:
#  - php-fpm-restart
