---
# File: main.yml
# Type: task
# Part: Apache2


## Install
- name: Apache2 | Install Apache
  apt: name=apache2 state={{ apache2_apt_state }}
- shell: apache2 -v | head -n1 | sed 's/.*Apache\/\(.*\)\s.*/\1/'
  register: apache2_version

## Install modules
- name: Apache2 | Install Apache modules
  apt: name={{ item }} state={{ apache2_apt_state }}
  with_items: apache2_apt_modules
  when: apache2_apt_modules is defined

# Install the default templates
# - name: Apache | Push configuration files
#   template:
#     src={{ item }}.j2
#     dest=/etc/apache2/{{ item }}
#     owner=root group=root mode=0644
#   with_items:
#   - envvars
#   - ports.conf

- name: Apache | Remove default index file from default docroot
  file: path=/var/www/index.html state=absent

- name: Remove default virtual host
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent

## Enable modules
- name: Apache2 | Enable modules
  command: a2enmod {{ item }} creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items: apache2_modules
  when: apache2_modules is defined
  notify: apache-restart

- name: Activate mod_rewrite
  apache2_module: name=rewrite state=present

## Setup custom location
- name: Apache2 | Setup directory
  file: state=directory dest={{ apache2_root }} mode=700 owner={{ apache2_user }} group={{ apache2_group }}

# - name: Apache2 | Move directory
#   shell: service apache2 stop; cp -rf /var/www/* {{ apache2_root }}; touch {{ apache2_root }}/.ansible; chown -R {{ apache2_user }}:{{ apache2_group }} {{ apache2_root }}; rm -rf /var/www
#     creates={{ apache2_root }}/.ansible
# - name: Apache2 | Link directories
#   file: state=link src={{ apache2_root }} path=/var/www force=yes
#   notify: apache-restart

## Check service
# This fails right now
# - name: Apache2 | Check service daemon
#   service: name=apache2 state=started
