---
# File: vhost_add.yml
# Part: Apache
#
# Description: Create a new virtual host
#
# Parameters:
# - $docroot : absolute docroot path
# - $vhost : virtualhost name
# - $create_docroot : create the docroot directory in the filesystem (if it doesn't exist) and push a default index file.
# - $port : 80 by default
# - $interfaces : * by default
#
# Dependencies-internal ([part:]type:filename):
# - handlers:handlers.yml
#
# OS familly: Ubuntu

- name: Apache | Virtualhost add | Create document root at $docroot
  file:
    path=$docroot
    state=directory
  when_boolean: $create_docroot

- name: Apache | Virtualhost add | Push default index file to docroot
  template:
    src=default_index.html.j2
    dest=$docroot/index.html
  when_boolean: $create_docroot

- name: Apache | Virtualhost add | Push virtualhost configuration template
  template:
    src=virtualhost.j2
    dest=/etc/apache2/sites-available/$vhost

- name: Apache | Virtualhost add | Activate virtual host $vhost
  command: /usr/sbin/a2ensite $vhost creates=/etc/apache2/sites-enabled/$vhost
  notify:
  - apache-reload
