---
- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  gather_facts: no

  tasks:
    - name: Install unzip
      apt: pkg=unzip state=latest update_cache=yes

    - name: Install MySQL client, server and related libraries
      apt: pkg={{ item }} state=latest
      with_items:
        - mysql-client
        - mysql-server
        - python-mysqldb

    - name: Install PHP and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - php5
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-imagick
        - php5-mysql
        - php5-xmlrpc

    - name: Install Apache and its modules
      apt: pkg={{ item }} state=latest
      with_items:
        - apache2
        - libapache2-mod-php5

    - name: Activate mod_rewrite
      apache2_module: name=rewrite state=present

    - name: Remove default virtual host
      file:
        path=/etc/apache2/sites-enabled/000-default.conf
        state=absent

    # - name: Deactivate default vhost
    #   command: a2dissite 000-default

    - name: Start MySQL service
      service:
        name: "mysql"
        state: started
        enabled: yes

    - name: Setup MySQL root password
      mysql_user:
        name: "root"
        password: "mysql"
        host: "{{ item }}"
        state: present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Setup MySQL creds for root user
      template:
        src: "templates/mysql"
        dest: "/root/.my.cnf"
        owner: "root"
        mode: 0600

    - name: Delete blank MySQL users
      mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Drop MySQL test database
      mysql_db: name=test state=absent

    - name: Put "vagrant" user in www-data group
      user:
        name: "vagrant"
        groups: "www-data"
        append: yes

    - name: Copy bash_profile
      command: cp /srv/config/bash_profile /home/vagrant/.bash_profile

    - name: Copy bash_aliases
      command: cp /srv/config/bash_aliases /home/vagrant/.bash_aliases

    # - name: Install Brew
    #   command: sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev

    # Make sure we have the latest npm version and the update checker module
	# npm install -g npm
	# npm install -g npm-check-updates

    - name: Ensure Apache is running
      service: name=apache2 state=restarted enabled=yes

  roles:
    - wp_cli
