---
- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  gather_facts: no

  tasks:
    - name: Install unzip
      apt: pkg=unzip state=latest update_cache=yes


    # - name: Install Apache and its modules
    #   apt: pkg={{ item }} state=latest
    #   with_items:
    #     - apache2
    #     - libapache2-mod-php5
    #
    # - name: Activate mod_rewrite
    #   apache2_module: name=rewrite state=present
    #
    # - name: Remove default virtual host
    #   file:
    #     path=/etc/apache2/sites-enabled/000-default.conf
    #     state=absent


    # - name: Install MySQL client, server and related libraries
    #   apt: pkg={{ item }} state=latest
    #   with_items:
    #     - mysql-client
    #     - mysql-server
    #     - python-mysqldb
    #
    # - name: Remove default virtual host
    #   file:
    #     path=/etc/apache2/sites-enabled/000-default.conf
    #     state=absent
    #
    # - name: Deactivate default vhost
    #   command: a2dissite 000-default
    #
    # - name: Start MySQL service
    #   service:
    #     name: "mysql"
    #     state: started
    #     enabled: yes
    #
    # - name: Setup MySQL root password
    #   mysql_user:
    #     name: "root"
    #     password: "mysql"
    #     host: "{{ item }}"
    #     state: present
    #   with_items:
    #     - "{{ ansible_hostname }}"
    #     - 127.0.0.1
    #     - ::1
    #     - localhost
    #
    # - name: Setup MySQL creds for root user
    #   template:
    #     src: "templates/mysql"
    #     dest: "/root/.my.cnf"
    #     owner: "root"
    #     mode: 0600
    #
    # - name: Delete blank MySQL users
    #   mysql_user:
    #     name: ""
    #     host: "{{ item }}"
    #     state: absent
    #   with_items:
    #     - "{{ ansible_hostname }}"
    #     - 127.0.0.1
    #     - ::1
    #     - localhost
    #
    # - name: Drop MySQL test database
    #   mysql_db: name=test state=absent
    - name: Put "vagrant" user in www-data group
      user:
        name: "vagrant"
        groups: "www-data"
        append: yes

    - name: Copy bash_profile
      command: cp /srv/config/bash_profile /home/vagrant/.bash_profile

    - name: Copy bash_aliases
      command: cp /srv/config/bash_aliases /home/vagrant/.bash_aliases

    - name: Ensure Apache is running
      service: name=apache2 state=restarted enabled=yes

  roles:
    - web/apache2 # Working
    - web/php # Done
    - web/nodejs # Done
    - database/mysql2 # Working
    - wp_cli # Done
    - composer # Done
