---

- include: main_centos.yml
  when: ansible_distribution == "CentOS"

- include: main_ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Push global vimrc
  template:
    src=vimrc.j2
    dest={{ ansible_env.HOME }}/.vimrc
